/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        "surface-dim": "#0b1326",
        "primary-container": "#4f46e5",
        primary: "#c3c0ff",
        "tertiary-fixed-dim": "#ffb695",
        "outline-variant": "#464555",
        "secondary-container": "#413f82",
        "on-surface": "#dae2fd",
        "on-error-container": "#ffdad6",
        "on-secondary": "#2a276a",
        "inverse-primary": "#4d44e3",
        "on-secondary-container": "#b0aef9",
        surface: "#0b1326",
        "on-secondary-fixed-variant": "#413f82",
        "on-tertiary-fixed": "#351000",
        "on-tertiary-fixed-variant": "#7b2f00",
        "surface-container-highest": "#2d3449",
        secondary: "#c3c0ff",
        "inverse-surface": "#dae2fd",
        "secondary-fixed-dim": "#c3c0ff",
        "on-tertiary": "#571f00",
        "secondary-fixed": "#e2dfff",
        "surface-container-lowest": "#060e20",
        "surface-container": "#171f33",
        "on-error": "#690005",
        "surface-variant": "#2d3449",
        outline: "#918fa1",
        "on-primary-container": "#dad7ff",
        "on-tertiary-container": "#ffd2be",
        "surface-container-high": "#222a3d",
        tertiary: "#ffb695",
        "on-primary-fixed": "#0f0069",
        error: "#ffb4ab",
        "error-container": "#93000a",
        "primary-fixed": "#e2dfff",
        background: "#0b1326",
        "tertiary-fixed": "#ffdbcc",
        "on-surface-variant": "#c7c4d8",
        "primary-fixed-dim": "#c3c0ff",
        "on-primary-fixed-variant": "#3323cc",
        "on-primary": "#1d00a5",
        "surface-tint": "#c3c0ff",
        "surface-bright": "#31394d",
        "on-background": "#dae2fd",
        "surface-container-low": "#131b2e",
        "inverse-on-surface": "#283044",
        "on-secondary-fixed": "#140f54",
        "tertiary-container": "#a44100",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Inter"],
        body: ["Inter"],
        label: ["Inter"],
      },
    },
  },
  darkMode: "class",
  plugins: [],
};
